apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["--requirepass", "$(redisPassword)"]
        # command: ["redis-server"]
        # args: ["/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
          name: redisport
        env:
        - name: MASTER
          value: "true"
        - name: redisPassword
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redisPassword
