apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  type: ClusterIP
  ports:
    - name: redis-service-port
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 6379
  selector:
    app: redis
