apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgres
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }}
