apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2023-02-08T20:47:55Z"
  name: postgres-secret
  namespace: {{ .Release.Namespace | quote }}
  resourceVersion: "44041"
  uid: fceaa0b8-bbcb-4fdc-8a15-d06682fc9d0a
data:
  username: {{ .Values.env.username | b64enc | quote }}
  password: {{ .Values.env.password | b64enc | quote }}
type: Opaque
