apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace | quote }}
data:
  username: {{ .Values.env.username | b64enc | quote }}
  password: {{ .Values.env.password | b64enc | quote }}
type: Opaque
