apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - name: postgres-service-port
      protocol: TCP
      port: {{ .Values.service.clusterIp.port }}
      targetPort: 5432
  selector:
    app: postgres

---
{{- if .Values.service.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-service-lb
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: LoadBalancer
  ports:
    - name: postgres-service-port-http
      protocol: TCP
      port: {{ .Values.service.loadBalancer.port }}
      targetPort: 5432
  selector:
    app: postgres
{{- end }}
