apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - name: postgres-service-port
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5432
  selector:
    app: postgres
