# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: redis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "5-alpine"

secret:
  redisPassword: "admin" # default password: admin

service:
  port: 6379
